import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";



export const metadata: Metadata = {
    title: "Flavor Dash",
    description: "Generated by create next app",
    icons: {
        icon: '/favicon-32x32.png',
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
            >
                {children}
                <Footer />
            </body>
        </html>
    );
}